"""Per-item verification result — the verifier agent's `output_type`."""

from pydantic import BaseModel, Field

from snaq_verify.domain.models.atwater_check import AtwaterCheck
from snaq_verify.domain.models.enums import ConfidenceLevel, Verdict
from snaq_verify.domain.models.food_item import NutritionPer100g
from snaq_verify.domain.models.nutrient_comparison import ItemVerdictBundle
from snaq_verify.domain.models.source_lookup import SelectedCandidate


class SourceEvidence(BaseModel):
    """One source's contribution to a verification."""

    source: str  # "usda", "off", "web"
    candidate: SelectedCandidate
    bundle: ItemVerdictBundle  # deltas of this candidate vs the input nutrition


class ItemVerification(BaseModel):
    """Verification result for a single FoodItem.

    This is the schema the verifier agent must produce (`output_type`).
    Every numeric field traces to a tool result; `summary` is generated by
    `format_human_summary` (a string template, not LLM prose).
    """

    item_id: str
    item_name: str
    reported_nutrition: NutritionPer100g
    verdict: Verdict
    confidence: ConfidenceLevel
    evidence: list[SourceEvidence] = Field(default_factory=list)
    proposed_correction: NutritionPer100g | None = None
    atwater_check_input: AtwaterCheck
    summary: str
    notes: list[str] = Field(default_factory=list)
